name: Client build & deploy

on:
  workflow_dispatch:
    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build --prod

    - name: Copy files to Azure VM
      uses: appleboy/scp-action@v1.0.0
      with:
        host: ${{ secrets.AZURE_VM_HOST }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        source: "dist/paybills-client/*"
        target: "/var/www/html/billminder-app"
